---
title: "Research"
output: 
  html_document:
    includes:
       in_header: GA_Script.html
---

<br>

# {.tabset .tabset-fade .tabset-pills} 

## Recent

These are some of the projects I worked on as a PhD student at the Agricultural 
and Resource Economics department at UC Berkeley.

### Microclimate Engineering for Climate Change Adaptation in Agriculture: The Case of California Pistachios

Trilnick, Itai and David Zilberman (2021), American Journal of Agricultural Economics 103(4): 1342-1358

#### Job Market Paper

Can farmers adapt to climate change by altering effective weather conditions on their fields? Existing technologies allow farmers to cool down plants by a few degrees during critical periods, reducing the damage from excess heat. With nonlinear effects of high temperatures on yields, slight cooling can bring significant gains in many crops. We call this approach “microclimate engineering” (MCE) and note that it could be useful as a climate change adaptation concept. Our case study deals with California pistachios, threatened by warming daytime temperatures in the winter. A new solution for sunlight reflection, based on products already used in other contexts and crops, could potentially help deal with this challenge. We develop a model to analyze grower choice and market outcomes with MCE for California pistachios. The expected increase in welfare for the period of 2020–2040 is assessed at 0.49–1.42 billion dollars under several scenarios. Simulation results show increases in consumer surplus and total welfare when MCE is available but decreases in aggregate grower profits. We also introduce market power to test its potential effects on the gains from MCE, finding mixed effects.

<a href="jmp.pdf" onClick= "gtag('event', 'Downloads', {'file':'jmp.pdf'});" target="_blank">download<i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>

---

### Agricultural GMOs - What We Know and Where Scientists Disagree
#### Published review paper
Population growth, climate change, and increasing human impact on land and aquatic
systems all pose significant challenges for current agricultural practices. Genetic engineering is a tool to speed up breeding for new varieties, which can help farmers and agricultural systems adapt to rapidly changing physical growing conditions, technology, and global markets. We review the current scientific literature and present the potential of genetically modified organisms (GMOs) from the perspectives of various stakeholders. GMOs increase yields, lower costs, and reduce the land and environmental footprint of agriculture. The benefits of this technology are shared among innovators, farmers, and consumers. Developing countries and poor farmers gain substantially from GMOs. Agricultural biotechnology is diverse, with many applications having different potential impacts. Its regulation needs to balance benefits and risks for each application. Excessive precaution prevents significant benefits. Increasing access to the technology and avoidance of excessive regulation will allow it to reach its potential.

David Zilberman, Tim Holland, and Itai Trilnick. <a href=sustainability_paper.pdf>"Agricultural GMOs - What We Know and Where Scientists Disagree?"</a>, *Sustainability* 10, 1514. (2018).

---

### Disability Insurance Reform and Labor Supply: Evidence from Israel
#### (With Yotam Shem-Tov)
In 2009, Israel reformed its Disability Insurance program, replacing a strict earning cap for beneficiaries with a gradual offset of benefits. This kind of program has been discussed in the US for over 20 years today. Using administrative data from Israel, the goal of this project is to estimate the effect of this reform on labor supply of beneficiaries, and on DI enrollment. Preliminary findings show strong labor supply effects on those beneficiaries who were employed prior to the reform; insignificant effect on those who didn't; and no effect on the characteristics of newly enrolled beneficiaries.

*work in progress*

---

---

## Past

I have a masters degree in environmental studies. In my thesis, I focused on solid waste policies in Israel. Solid waste ("garbage") is a major environmental issue, and I hope to keep doing research on it.

### Should we blame the rich for clogging our landfills?
#### (With Alon Tal)

**Abstract:** Conventional wisdom often holds that relatively high consumption levels among the affluent contributes to the generation of high volumes of municipal solid waste (MSW). Comparing data from different cities in Israel suggests otherwise. Regression analysis reveals that aggregate per-capita waste outputs of cities are only vaguely correlated with their socio-economic indicators. In fact, the apparent ‘hedonic’ waste of the richest cities, compared with the average ones, accounts for only about 2% of the total waste production. Israel’s main economic area, the Tel Aviv district, produces a quarter more MSW per capita than other districts, suggesting a need for special attention by policy makers. A surprisingly strong predictor of MSW per capita is water consumption by municipalities, dedicated for public gardening. The trimmings of the municipal landscape constituting an unobserved fraction of total MSW data, are estimated to be responsible for 15% of Israel’s MSW, making it an additional target area for consideration and intervention.

Trilnick, Itai, and Alon Tal. <a href="http://wmr.sagepub.com/content/32/2/91.short" target="_blank">"Should we blame the rich for clogging our landfills?"</a>, *Waste Management & Research* 32.2 (2014): 91-96.


<a href="trilnick2014should.pdf" target="_blank">draft-<i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>


### What Drives Municipal Solid Waste Policy Making? An Empirical Assessment of the Effectiveness of Tipping Fees and Other Factors in Israel
#### (With Alon Tal)

**Abstract:** What factors influence the waste policy of local authorities? While central governments make efforts to promote recycling, the major players in municipal waste management are local authorities. This paper explores the factors influencing waste policies of local authorities in Israel in light of the new landfill tax legislated in 2007. Based on interviews with officials overseeing waste management and other stakeholders, a model of waste policy making in local authorities is proposed. A survey among waste officials of local authorities then evaluates the influence of general and specific factors on associated municipal policies. Cost of landfilling and a new landfill tax, is reported as highly influential on waste policies. Other factors, such as the Mayor's motivation, managerial capacity in the municipality, and recycling markets are also highly influential. While the cost of landfilling is easily targeted by the central government, the latter factors are seldom addressed. 

Trilnick, Itai, and Alon Tal. <a href="http://www.ingentaconnect.com/content/jswt/jswt/2014/00000040/00000004/art00008" target="_blank">"What Drives Municipal Solid Waste Policy Making? An Empirical Assessment of the Effectiveness of Tipping Fees and Other Factors in Israel."</a>, *The Journal of Solid Waste Technology and Management* 40.4 (2014): 364-374.

<a href="trilnick2014whatdrives.pdf" target="_blank">draft-<i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
